<?php

declare(strict_types=1);

namespace Angeo\AeoAudit\Model\Checker;

use Angeo\AeoAudit\Model\Report\CheckResult;
use Magento\Store\Api\Data\StoreInterface;

/**
 * Validates /llms.jsonl — machine-readable catalog for AI pipelines.
 *
 * 3.1.1: the checker is now RECORD-TYPE AWARE. Real-world llms.jsonl files
 * (including those generated by angeo/module-llms-txt) are mixed-type: they
 * contain product records alongside category records and store-information
 * records. Previously every line was validated as if it were a product, so a
 * perfectly valid store-info record without "title"/"name"/"price" produced
 * a false-positive FAIL ("name/title missing in N records").
 *
 * Type resolution per record:
 *  1. An explicit type field ("type", "@type", "record_type", "kind",
 *     "entity_type", "content_type") wins — its value is normalized and
 *     mapped to product / category / store / page / other.
 *  2. Without an explicit type, a record carrying any eCommerce field
 *     (price / sku / currency / brand / regular_price) is inferred to be
 *     a product; everything else is treated as a generic record.
 *
 * Validation matrix:
 *  - product  → "url" required (FAIL), name/title required (FAIL),
 *               eCommerce-field coverage tracked (WARN if >80% missing)
 *  - category → "url" and name expected (WARN only)
 *  - store / page / other → no field requirements; counted and reported
 *    in details only (these records describe the store, not the catalog)
 *  - invalid JSON on any line is always a FAIL
 *  - MIN_RECORDS sanity threshold applies to PRODUCT records, so a file
 *    padded with metadata lines can't mask an empty catalog
 */
class LlmsJsonlChecker extends AbstractChecker
{
    /** Name field aliases — at least one must be present on a product. */
    private const NAME_FIELDS = ['title', 'name', 'product_name', 'label'];

    /** eCommerce fields — at least one must be present on a product. */
    private const ECOM_FIELDS = ['price', 'sku', 'currency', 'brand', 'regular_price'];

    /**
     * Strong product signals used for TYPE INFERENCE when no explicit type
     * field exists. Deliberately narrower than ECOM_FIELDS: a store-info
     * record may legitimately carry "currency" or "brand" without being a
     * product, but "price" / "sku" / "regular_price" are product-specific.
     */
    private const PRODUCT_SIGNALS = ['price', 'sku', 'regular_price'];

    /** Fields that may declare the record type explicitly. */
    private const TYPE_FIELDS = ['type', '@type', 'record_type', 'kind', 'entity_type', 'content_type'];

    private const TYPE_PRODUCT  = 'product';
    private const TYPE_CATEGORY = 'category';
    private const TYPE_STORE    = 'store';
    private const TYPE_PAGE     = 'page';
    private const TYPE_OTHER    = 'other';

    /** Normalized explicit-type values → internal record type. */
    private const TYPE_MAP = [
        'product'      => self::TYPE_PRODUCT,
        'products'     => self::TYPE_PRODUCT,
        'offer'        => self::TYPE_PRODUCT,
        'variant'      => self::TYPE_PRODUCT,
        'sku'          => self::TYPE_PRODUCT,
        'category'     => self::TYPE_CATEGORY,
        'categories'   => self::TYPE_CATEGORY,
        'collection'   => self::TYPE_CATEGORY,
        'store'        => self::TYPE_STORE,
        'store_info'   => self::TYPE_STORE,
        'storeinfo'    => self::TYPE_STORE,
        'shop'         => self::TYPE_STORE,
        'organization' => self::TYPE_STORE,
        'merchant'     => self::TYPE_STORE,
        'site'         => self::TYPE_STORE,
        'page'         => self::TYPE_PAGE,
        'cms'          => self::TYPE_PAGE,
        'cms_page'     => self::TYPE_PAGE,
        'article'      => self::TYPE_PAGE,
        'faq'          => self::TYPE_PAGE,
        'policy'       => self::TYPE_PAGE,
    ];

    private const MIN_PRODUCT_RECORDS = 5;
    private const MAX_BYTES           = 10_485_760; // 10 MB
    private const STALE_DAYS          = 7;
    private const MAX_LINES_TO_CHECK  = 20;

    public function getName(): string
    {
        return 'llms.jsonl — machine-readable catalog';
    }

    public function getCode(): string
    {
        return 'llms_jsonl';
    }

    public function getWeight(): float
    {
        return 0.75;
    }

    public function getFixCommand(): string
    {
        return 'composer require angeo/module-llms-txt';
    }

    public function check(StoreInterface $store): CheckResult
    {
        $base = $this->urlSampler->getBaseUrl($store);
        $url  = $base . '/llms.jsonl';

        [$status, $body, $headers] = $this->fetchWithHeaders($url);

        if ($status !== 200 || empty($body)) {
            return $this->fail(
                'llms.jsonl not found (HTTP ' . ($status ?: 'error') . ').',
                'Install angeo/module-llms-txt and run: bin/magento angeo:llms:generate'
                . ' — generates both llms.txt and llms.jsonl',
                ['url' => $url]
            );
        }

        $issues   = [];
        $warnings = [];
        $size     = strlen($body);

        $rawLines = explode("\n", trim($body));
        $lines    = array_values(array_filter($rawLines, static fn(string $l) => trim($l) !== ''));
        $total    = count($lines);

        $invalidLines     = [];
        $productIssues    = []; // field => count — FAIL-level, products only
        $categoryWarnings = []; // field => count — WARN-level
        $typeCounts       = [
            self::TYPE_PRODUCT  => 0,
            self::TYPE_CATEGORY => 0,
            self::TYPE_STORE    => 0,
            self::TYPE_PAGE     => 0,
            self::TYPE_OTHER    => 0,
        ];
        $productsMissingEcom = 0;
        $checked             = 0;

        foreach ($lines as $lineNum => $line) {
            if ($checked >= self::MAX_LINES_TO_CHECK) {
                break;
            }
            $checked++;

            $decoded = json_decode($line, true);
            if ($decoded === null) {
                $invalidLines[] = 'line ' . ($lineNum + 1) . ': ' . json_last_error_msg();
                continue;
            }
            if (!is_array($decoded)) {
                $invalidLines[] = 'line ' . ($lineNum + 1) . ': not a JSON object';
                continue;
            }

            $record = array_change_key_case($decoded, CASE_LOWER);
            $type   = $this->resolveRecordType($record);
            $typeCounts[$type]++;

            $hasUrl  = !empty($record['url']);
            $hasName = $this->hasAnyField($record, self::NAME_FIELDS);
            $hasEcom = $this->hasAnyField($record, self::ECOM_FIELDS);

            if ($type === self::TYPE_PRODUCT) {
                // Products are what AI shopping pipelines consume — strict.
                if (!$hasUrl) {
                    $productIssues['url'] = ($productIssues['url'] ?? 0) + 1;
                }
                if (!$hasName) {
                    $productIssues['name/title'] = ($productIssues['name/title'] ?? 0) + 1;
                }
                if (!$hasEcom) {
                    $productsMissingEcom++;
                }
            } elseif ($type === self::TYPE_CATEGORY) {
                // Categories should be linkable and labelled — advisory only.
                if (!$hasUrl) {
                    $categoryWarnings['url'] = ($categoryWarnings['url'] ?? 0) + 1;
                }
                if (!$hasName) {
                    $categoryWarnings['name/title'] = ($categoryWarnings['name/title'] ?? 0) + 1;
                }
            }
            // store / page / other records carry metadata (store info, policies,
            // CMS content). They have no required fields — counted in details.
        }

        $emptyInMiddle = 0;
        $rawLineCount  = count($rawLines);
        foreach ($rawLines as $i => $line) {
            if ($i > 0 && $i < $rawLineCount - 1 && trim($line) === '') {
                $emptyInMiddle++;
            }
        }
        if ($emptyInMiddle > 0) {
            $warnings[] = sprintf('%d empty line(s) in the middle — may break streaming JSON parsers', $emptyInMiddle);
        }

        if (!empty($invalidLines)) {
            $issues[] = sprintf(
                '%d invalid JSON line(s): %s',
                count($invalidLines),
                implode('; ', array_slice($invalidLines, 0, 3))
            );
        }

        $checkedProducts = $typeCounts[self::TYPE_PRODUCT];

        foreach ($productIssues as $field => $count) {
            $issues[] = sprintf(
                '"%s" missing in %d/%d checked product records',
                $field,
                $count,
                $checkedProducts
            );
        }

        foreach ($categoryWarnings as $field => $count) {
            $warnings[] = sprintf(
                '"%s" missing in %d/%d checked category records',
                $field,
                $count,
                $typeCounts[self::TYPE_CATEGORY]
            );
        }

        if ($productsMissingEcom > 0 && $checkedProducts > 0) {
            $pct = (int) round($productsMissingEcom / $checkedProducts * 100);
            if ($pct > 80) {
                $warnings[] = sprintf(
                    '%d%% of product records missing all eCommerce fields (price/sku/currency)'
                    . ' — check feed generation',
                    $pct
                );
            }
        }

        // Sanity threshold counts PRODUCT records within the checked sample:
        // a catalog file consisting only of store/category metadata is not a
        // usable product feed. If the sample window was exhausted (more lines
        // exist than we inspected), skip the warning — the rest of the file
        // likely contains the products.
        if ($checkedProducts < self::MIN_PRODUCT_RECORDS && $checked === $total) {
            $warnings[] = sprintf(
                'Only %d product record(s) of %d total — expected more for a product catalog'
                . ' (check generation settings)',
                $checkedProducts,
                $total
            );
        }

        $lastModified = $headers['last-modified'] ?? null;
        if ($lastModified) {
            $modTime = strtotime($lastModified);
            if ($modTime && (time() - $modTime) > (self::STALE_DAYS * 86400)) {
                $days = (int) round((time() - $modTime) / 86400);
                $warnings[] = sprintf(
                    'llms.jsonl is %d days old — enable cron or run: bin/magento angeo:llms:generate',
                    $days
                );
            }
        }

        if ($size > self::MAX_BYTES) {
            $warnings[] = sprintf(
                'File is %.1fMB — consider serving as llms.jsonl.gz for faster AI crawler access',
                $size / 1_048_576
            );
        }

        $details = [
            'url'               => $url,
            'size_bytes'        => $size,
            'total_records'     => $total,
            'checked'           => $checked,
            'record_types'      => array_filter($typeCounts),
            'invalid_lines'     => $invalidLines,
            'product_issues'    => $productIssues,
            'category_warnings' => $categoryWarnings,
            'last_modified'     => $lastModified,
        ];

        if (!empty($issues)) {
            return $this->fail(
                sprintf('llms.jsonl has %d critical issue(s): %s', count($issues), $issues[0]),
                implode(' | ', array_merge($issues, $warnings)),
                $details
            );
        }

        if (!empty($warnings)) {
            return $this->warn(
                sprintf('llms.jsonl valid (%d records) — %d improvement(s)', $total, count($warnings)),
                implode(' | ', $warnings),
                $details
            );
        }

        return $this->pass(
            sprintf(
                'llms.jsonl valid — %d records (%d products), all required fields present.',
                $total,
                $checkedProducts
            ),
            $details
        );
    }

    /**
     * Resolve the record type: explicit type field first, then inference.
     *
     * @param array<string, mixed> $record Lower-cased-key record
     */
    private function resolveRecordType(array $record): string
    {
        foreach (self::TYPE_FIELDS as $typeField) {
            if (!isset($record[$typeField]) || !is_scalar($record[$typeField])) {
                continue;
            }
            $value = strtolower(trim((string) $record[$typeField]));
            // Normalize separators: "store-info" / "Store Info" → "store_info"
            $value = str_replace([' ', '-'], '_', $value);
            if (isset(self::TYPE_MAP[$value])) {
                return self::TYPE_MAP[$value];
            }
            // Unknown explicit type — trust the producer that it is NOT a
            // product rather than failing it against product rules.
            return self::TYPE_OTHER;
        }

        // No explicit type: only strong commerce signals (price/sku) make a
        // record a product — "currency"/"brand" alone do not (store info).
        return $this->hasAnyField($record, self::PRODUCT_SIGNALS)
            ? self::TYPE_PRODUCT
            : self::TYPE_OTHER;
    }

    /**
     * @param array<string, mixed> $record Lower-cased-key record
     * @param string[] $fields
     */
    private function hasAnyField(array $record, array $fields): bool
    {
        foreach ($fields as $field) {
            if (!empty($record[$field])) {
                return true;
            }
        }
        return false;
    }
}
